### PR TITLE
Feature/redesign

### PR DESCRIPTION
**Pull request by kevinmpowell**
@nathanacurtis this redesign is ready for review & edits

### CODE REVIEW

**Comment by nathanacurtis** [comment]
image

While we aren't making a responsive solution, you can still `max-width` the text block to not collide with crop channels.

**Comment by nathanacurtis** [comment]
- [ ] Rename repository with prepended `esds-`

**Comment by nathanacurtis** [comment]
Decrease maximum width and adjust fields commensurately:

- [ ] Reduce max width per row from `1200` to `1000`
- [ ] Reduce width of size, line height, top, bottom crop fields to `flex: 0 0 3em, width: 3em`

**Comment by nathanacurtis** [comment]
- [ ] Configure the orange/blue to default to 9 & 8 for Lato by default (the already optimized settings).

**Comment by nathanacurtis** [comment]
image

- [ ] align default bottom padding to match top padding of step 1 row

**Comment by nathanacurtis** [comment]
image

- [ ] The thumbnail isn't presenting as square but says 100x100. Huh?

**Comment by nathanacurtis** [comment]
image

- [ ] Add a white background to the code block.
- [ ] Make Copy Code title case, not all caps.

**Comment by nathanacurtis** [comment]
image

- [ ] Reduce hero inset by one stop

**Comment by nathanacurtis** [comment]
image

- [ ] Chrome uses lime for inset inspection. Why are we using lemon?

**Comment by nathanacurtis** [comment]
- [ ] Change "64px font with 20px padding" to "64px size in 20px inset"
- [ ] Change "16px font with 20px padding" to "16px size in 20px inset"
- [ ] Change "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt incidunt veniam itaque inventore, placeat, mollitia unde reiciendis."  to "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt incidunt veniam."

**Comment by nathanacurtis** [comment]
For comments, change to:

```
@mixin text-crop() {

    // Configured in Step 1
    $top-crop: 9;
    $bottom-crop: 8;
    $crop-font-size: 36;
    $crop-line-height: 1.2;

    // Apply values to calculate em-based margins that work with any font size
    $dynamic-top-crop: max(($top-crop + ($line-height - $crop-line-height) * ($crop-font-size / 2)), 0) / $crop-font-size;
    $dynamic-bottom-crop: max(($bottom-crop + ($line-height - $crop-line-height) * ($crop-font-size / 2)), 0) / $crop-font-size;

    // Mixin output
    line-height: $line-height;
```

**Comment by kevinmpowell** [comment]
Responding to what I didn't fix:

> Reduce width of size, line height, top, bottom crop fields to flex: 0 0 3em, width: 3em

Reducing the width of the fields that much causes label wrapping and spin box overlap. I think we should leave as-is:
screen shot 2017-11-03 at 10 57 58 am
screen shot 2017-11-03 at 10 58 41 am

---
> align default bottom padding to match top padding of step 1 row

Doing this would result in the bottom slider extending beyond the step 1 row. I've reduced it a bit, but this is as far as it can go:
screen shot 2017-11-03 at 11 06 53 am

---
> Reduce hero inset by one stop

Hero inset in esds-library isn't using tokens, so I halved the value in the text-crop css

screen shot 2017-11-03 at 11 17 38 am
*esds-library*

screen shot 2017-11-03 at 11 18 48 am
*esds-text-crop*

**Comment by kevinmpowell** [comment]
@nathanacurtis don't we still want a link to the GitHub repo and a "tweet this tool" action?

**Comment by nathanacurtis** [comment]
- I'm unopinionated for now about "Tweet this tool"
- The comments revisions remains incomplete
- I'm thinking the bottom baseline scrubber could be not bound to the inset and actually span over it, meaning that the bottom inset of step 2 could still be smaller.

**Pull request merged**
